"""Render docs/templates/*.md.tmpl into the committed markdown docs.

All numbers come from results/**/metrics.json (hard rule 1). Tables are built here in
code; prose and scalar placeholders live in the templates.

    .venv\\Scripts\\python.exe scripts\\render_docs.py          # write docs
    .venv\\Scripts\\python.exe scripts\\render_docs.py --check  # exit 1 if any doc is stale
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from harness.render import NOT_MEASURED, iec, lookup, render  # noqa: E402
from harness.results import REPO_ROOT, load_all  # noqa: E402

TEMPLATES = REPO_ROOT / "docs" / "templates"

# template name -> output path (relative to repo root)
OUTPUTS = {
    "README.md.tmpl": "README.md",
    "SYSTEM_INFO.md.tmpl": "SYSTEM_INFO.md",
    "KV_MEMORY_MODEL.md.tmpl": "docs/KV_MEMORY_MODEL.md",
    "IMPLEMENTATION_PLAN.md.tmpl": "docs/IMPLEMENTATION_PLAN.md",
    "RESEARCH_LOG.md.tmpl": "docs/RESEARCH_LOG.md",
    "PHASE_0.md.tmpl": "docs/phases/PHASE_0.md",
}

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/render_docs.py from docs/templates/{name}. "
    "Edit the template, not this file. Numbers come from results/**/metrics.json. -->\n\n"
)


# ---- formatting helpers ----------------------------------------------------------------


def gbps(v: float | None) -> str:
    return NOT_MEASURED if v is None else f"{v / 1e9:.2f}"


def rng(a: Mapping[str, Any] | None, fmt: Callable[[float], str], show_range: bool = True) -> str:
    """'median (min–max)' across independent runs."""
    if not a or not a.get("n_runs"):
        return NOT_MEASURED
    med = fmt(a["median"])
    if not show_range or a["n_runs"] < 2:
        return med
    return f"{med} ({fmt(a['min'])}–{fmt(a['max'])})"


def ms(v: float) -> str:
    return f"{v * 1e3:.3g} ms" if v < 1 else f"{v:.2f} s"


def table(header: list[str], rows: list[list[str]], align: list[str] | None = None) -> str:
    align = align or ["---"] * len(header)
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(align) + " |"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


# ---- blocks ------------------------------------------------------------------------------


def block_pcie_curve(ctx: Mapping[str, Any]) -> str:
    curve = lookup(ctx, "phase0.analysis.pcie.curve")
    if not isinstance(curve, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in curve:
        rows.append(
            [iec(r["size_bytes"])]
            + [rng(r[k], lambda v: f"{v / 1e9:.2f}") for k in ("pinned_h2d", "pinned_d2h", "pageable_h2d", "pageable_d2h")]
        )
    return table(
        ["Transfer size", "Pinned H2D", "Pinned D2H", "Pageable H2D", "Pageable D2H"],
        rows,
        ["---:", "---:", "---:", "---:", "---:"],
    )


def block_pcie_knees(ctx: Mapping[str, Any]) -> str:
    p = lookup(ctx, "phase0.analysis.pcie")
    if not isinstance(p, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = []
    for key, label in (("pinned_h2d", "Pinned H2D"), ("pinned_d2h", "Pinned D2H"), ("pageable_h2d", "Pageable H2D"), ("pageable_d2h", "Pageable D2H")):
        d = p[key]
        rows.append(
            [
                label,
                rng(d["asymptote_bps"], lambda v: f"{v / 1e9:.2f} GB/s"),
                rng(d["knee50_bytes"], iec),
                rng(d["knee80_bytes"], iec),
                rng(d["fit_t0_s"], lambda v: f"{v * 1e6:.0f} µs"),
                rng(d["fit_knee80_bytes"], iec),
            ]
        )
    return table(
        ["Path", "Asymptotic bandwidth", "50% knee (empirical)", "80% knee (empirical)", "Per-transfer overhead t0 (fit)", "80% knee (fit)"],
        rows,
        ["---", "---:", "---:", "---:", "---:", "---:"],
    )


def block_attention(ctx: Mapping[str, Any]) -> str:
    rows_in = lookup(ctx, "phase0.analysis.vram.decode_attention")
    if not isinstance(rows_in, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for a in rows_in:
        for name, b in a["backends"].items():
            best = " **(best)**" if name == a["best_backend"] else ""
            rows.append(
                [
                    f"{a['ctx_len']:,}",
                    f"`{name}`{best}",
                    rng(b["seconds_per_call"], ms),
                    rng(b["kv_scan_bps"], lambda v: f"{v / 1e9:.1f}"),
                    f"{b['max_rel_err_vs_math']:.1e}",
                    "yes" if b["correct"] else "**no**",
                ]
            )
    return table(
        ["Context (tokens, 1 layer)", "SDPA path", "Time per call", "KV scanned (GB/s)", "Max rel. error vs math", "Within tolerance"],
        rows,
        ["---:", "---", "---:", "---:", "---:", "---"],
    )


def block_overlap(ctx: Mapping[str, Any]) -> str:
    o = lookup(ctx, "phase0.analysis.overlap")
    if not isinstance(o, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [
        ["Compute kernel + pinned H2D", rng(o["compute_h2d_overlap"], lambda v: f"{v:.2f}")],
        ["Compute kernel + pinned D2H", rng(o["compute_d2h_overlap"], lambda v: f"{v:.2f}")],
        ["Pinned H2D + pinned D2H", rng(o["h2d_d2h_overlap"], lambda v: f"{v:.2f}")],
    ]
    return table(["Concurrent pair (separate CUDA streams)", "Overlap fraction (1 = max, 0 = sum)"], rows, ["---", "---:"])


def block_cpu_threads(ctx: Mapping[str, Any]) -> str:
    c = lookup(ctx, "phase0.analysis.cpu")
    if not isinstance(c, Mapping):
        return f"_{NOT_MEASURED}_"
    threads = c["threads"]
    rows = []
    for r in c["grid"]:
        rows.append([f"{r['tokens']:,}"] + [rng(r[f"partial_attn_t{t}"], ms, show_range=False) for t in threads])
    return table(["Tokens / layer"] + [f"{t} thr" for t in threads], rows, ["---:"] * (len(threads) + 1))


def block_cpu_vs_gpu(ctx: Mapping[str, Any]) -> str:
    c = lookup(ctx, "phase0.analysis.cpu.partial_attn_best")
    if not isinstance(c, list):
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            f"{r['tokens']:,}",
            rng(r["best_seconds"], ms),
            ", ".join(str(t) for t in r["best_threads"]),
            rng(r["gpu_fp32_seconds"], ms),
            rng(r["cpu_over_gpu"], lambda v: f"{v:.1f}×"),
        ]
        for r in c
    ]
    return table(
        ["Tokens / layer", "CPU best", "Best thread count per run", "GPU (same op, fp32)", "CPU / GPU"],
        rows,
        ["---:", "---:", "---", "---:", "---:"],
    )


def block_design(ctx: Mapping[str, Any]) -> str:
    d = lookup(ctx, "phase0.analysis.design")
    if not isinstance(d, Mapping) or not d.get("available"):
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in d["rows"]:
        rows.append(
            [
                f"{r['tokens_per_layer']:,}",
                iec(r["kv_bytes_per_layer_bf16"]),
                ms(r["fetch_one_transfer_s"]),
                ms(r["fetch_with_1thread_gather_s"]),
                ms(r["fetch_64tok_blocks_s"]),
                ms(r["gpu_attention_s"]) if "gpu_attention_s" in r else NOT_MEASURED,
                f"{r['fetch_over_gpu_attention']:.1f}×" if "fetch_over_gpu_attention" in r else "–",
                ms(r["cpu_partial_attn_s"]) if "cpu_partial_attn_s" in r else NOT_MEASURED,
                f"{r['cpu_over_fetch_one']:.1f}×" if "cpu_over_fetch_one" in r else "–",
                f"{r['cpu_over_fetch_blocks']:.1f}×" if "cpu_over_fetch_blocks" in r else "–",
            ]
        )
    return table(
        [
            "Non-resident tokens / layer",
            "KV bytes (bf16)",
            "(a) 1 transfer, already contiguous",
            "(a) 1-thread gather + 1 transfer",
            "(a) 64-token block transfers",
            "GPU attention (best kernel)",
            "contiguous fetch ÷ GPU attn",
            "(c) CPU partial attention",
            "(c) ÷ contiguous fetch",
            "(c) ÷ block fetch",
        ],
        rows,
        ["---:"] * 10,
    )


def block_nvidia_smi(ctx: Mapping[str, Any]) -> str:
    smi = lookup(ctx, "phase0.feasibility.run_1.system.software_gpu.nvidia_smi")
    if not isinstance(smi, Mapping):
        return f"_{NOT_MEASURED}_"
    return table(["nvidia-smi field", "Value"], [[f"`{k}`", str(v)] for k, v in smi.items()])


def block_hags(ctx: Mapping[str, Any]) -> str:
    host = lookup(ctx, "phase0.feasibility.run_1.system.host")
    if not isinstance(host, Mapping):
        return NOT_MEASURED
    v = host.get("hags_hwschmode")
    # The probe ran; a null means the registry value does not exist (Windows default).
    return {None: "registry value absent (Windows default)", 1: "1 (off)", 2: "2 (on)"}.get(v, str(v))


def block_env_vars(ctx: Mapping[str, Any]) -> str:
    env = lookup(ctx, "phase0.feasibility.run_1.system.software_gpu.env")
    if not isinstance(env, Mapping):
        return f"_{NOT_MEASURED}_"
    # None here means "unset in the benchmark process", which is a recorded fact, not a gap.
    return table(["Variable", "Value during benchmarks"], [[f"`{k}`", "(unset)" if v is None else f"`{v}`"] for k, v in env.items()])


def block_nvme(ctx: Mapping[str, Any]) -> str:
    n = lookup(ctx, "phase0.analysis.nvme")
    if not isinstance(n, Mapping) or not n.get("measured"):
        return f"_{NOT_MEASURED}_"
    rows = [
        ["Sequential, 1 MiB reads", rng(n["sequential_bps"], lambda v: f"{v / 1e9:.2f} GB/s"), "–"],
        [
            "Random 4 KiB",
            rng(n["random"]["4096"]["bps"], lambda v: f"{v / 1e6:.0f} MB/s"),
            rng(n["random"]["4096"]["iops"], lambda v: f"{v:,.0f}"),
        ],
        [
            "Random 128 KiB (one 64-token layer block)",
            rng(n["random"]["131072"]["bps"], lambda v: f"{v / 1e6:.0f} MB/s"),
            rng(n["random"]["131072"]["iops"], lambda v: f"{v:,.0f}"),
        ],
    ]
    return table(["Pattern (QD1, unbuffered)", "Throughput", "IOPS"], rows, ["---", "---:", "---:"])


def block_bandwidth_ladder(ctx: Mapping[str, Any]) -> str:
    a = lookup(ctx, "phase0.analysis")
    if not isinstance(a, Mapping):
        return f"_{NOT_MEASURED}_"
    big_attn = max(a["vram"]["decode_attention"], key=lambda r: r["ctx_len"])
    best = big_attn["backends"][big_attn["best_backend"]]["kv_scan_bps"]
    cpu64 = max(a["cpu"]["partial_attn_best"], key=lambda r: r["tokens"])
    kv_fp32 = 2 * cpu64["tokens"] * 8 * 64 * 4
    t = cpu64["best_seconds"]
    # Rate is 1/time, so the fastest run (min time) is the max rate.
    cpu_rate = {"n_runs": t["n_runs"], "median": kv_fp32 / t["median"], "min": kv_fp32 / t["max"], "max": kv_fp32 / t["min"]}
    rows = [
        ["VRAM device-to-device copy", rng(a["vram"]["d2d_copy_bps"], gbps)],
        [f"GPU decode attention KV scan (`{big_attn['best_backend']}`, {big_attn['ctx_len']:,} tokens)", rng(best, gbps)],
        ["PCIe pinned H2D (asymptote)", rng(a["pcie"]["pinned_h2d"]["asymptote_bps"], gbps)],
        ["PCIe pinned D2H (asymptote)", rng(a["pcie"]["pinned_d2h"]["asymptote_bps"], gbps)],
        ["PCIe pageable H2D (asymptote)", rng(a["pcie"]["pageable_h2d"]["asymptote_bps"], gbps)],
        ["Host memcpy, 1 thread", rng(a["cpu"]["host_memcpy_bps_1thread"], gbps)],
        [f"CPU partial attention KV rate (fp32, {cpu64['tokens']:,} tokens, best threads)", rng(cpu_rate, gbps)],
    ]
    if a["nvme"].get("measured"):
        rows += [
            ["NVMe sequential read", rng(a["nvme"]["sequential_bps"], gbps)],
            ["NVMe random 128 KiB read", rng(a["nvme"]["random"]["131072"]["bps"], gbps)],
        ]
    return table(["Path", "GB/s, median (min–max) across runs"], rows, ["---", "---:"])


def block_kv_models(ctx: Mapping[str, Any]) -> str:
    models = lookup(ctx, "phase0.kv_memory_model.models")
    if not isinstance(models, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for m in models:
        src = f"`{m['config_source']}`" + (" (mirror)" if m["used_mirror"] else "")
        rows.append(
            [
                f"**{m['key']}**",
                m["role"],
                src,
                str(m["num_hidden_layers"]),
                str(m["num_attention_heads"]),
                str(m["num_key_value_heads"]),
                str(m["head_dim"]),
                f"{m['gqa_group']}:1",
                iec(m["kv_bytes_per_token_bf16"]),
                iec(m["weights_bytes_safetensors"]) if m.get("weights_bytes_safetensors") else NOT_MEASURED,
            ]
        )
    return table(
        ["Model", "Role", "config.json source", "Layers", "Q heads", "KV heads", "head_dim", "GQA", "KV / token (bf16)", "Weights on disk"],
        rows,
        ["---", "---", "---", "---:", "---:", "---:", "---:", "---:", "---:", "---:"],
    )


def block_kv_contexts(ctx: Mapping[str, Any]) -> str:
    kv = lookup(ctx, "phase0.kv_memory_model")
    if not isinstance(kv, Mapping):
        return f"_{NOT_MEASURED}_"
    contexts = kv["contexts"]
    rows = [[f"**{m['key']}**"] + [iec(m["kv_bytes_by_context_bf16"][str(c)]) for c in contexts] for m in kv["models"]]
    return table(["Model"] + [f"{c // 1024}K" for c in contexts], rows, ["---"] + ["---:"] * len(contexts))


def block_kv_fit(ctx: Mapping[str, Any]) -> str:
    kv = lookup(ctx, "phase0.kv_memory_model")
    if not isinstance(kv, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = []
    for m in kv["models"]:
        fit = m.get("max_context_bf16_in_free_vram")
        rows.append(
            [
                f"**{m['key']}**",
                f"{m['max_position_embeddings']:,}" if m.get("max_position_embeddings") else NOT_MEASURED,
                f"{fit:,}" if fit is not None else NOT_MEASURED,
                f"{m['vocab_size']:,}",
                iec(m["prefill_logits_bytes_64k"]["bf16"]),
                iec(m["prefill_logits_bytes_64k"]["fp32"]),
            ]
        )
    return table(
        ["Model", "max_position_embeddings", "Max bf16 KV tokens in measured free VRAM (after weights)", "Vocab", "64K full logits (bf16)", "64K full logits (fp32)"],
        rows,
        ["---", "---:", "---:", "---:", "---:", "---:"],
    )


def block_budget_sweep(ctx: Mapping[str, Any]) -> str:
    s = lookup(ctx, "phase0.kv_memory_model.primary_budget_sweep")
    if not isinstance(s, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [[f"{100 * r['budget']:g}%", iec(r["gpu_kv_bytes"])] for r in s["rows"]]
    return table(["GPU KV budget", f"GPU-resident KV at {s['ctx_len'] // 1024}K ({s['model']}, bf16)"], rows, ["---:", "---:"])


def block_device_properties(ctx: Mapping[str, Any]) -> str:
    props = lookup(ctx, "phase0.feasibility.run_1.system.software_gpu.cuda_device_properties")
    if not isinstance(props, Mapping):
        return f"_{NOT_MEASURED}_"
    return table(["Field", "Value"], [[f"`{k}`", f"`{v}`"] for k, v in props.items()], ["---", "---"])


def block_driver_attributes(ctx: Mapping[str, Any]) -> str:
    attrs = lookup(ctx, "phase0.analysis.overlap.driver_attributes_run1")
    if not isinstance(attrs, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [[f"`CU_DEVICE_ATTRIBUTE_{k}`", str(v)] for k, v in attrs.items() if k not in ("ok", "source")]
    return table(["Driver attribute (cuDeviceGetAttribute)", "Value"], rows, ["---", "---:"])


def block_ram(ctx: Mapping[str, Any]) -> str:
    dimms = lookup(ctx, "phase0.feasibility.run_1.system.host.ram_dimms")
    if not isinstance(dimms, list):
        return f"_{NOT_MEASURED}_"
    rows = [
        [d.get("DeviceLocator") or "?", iec(int(d["Capacity"])), f"{d['Speed']} MT/s", f"{d['ConfiguredClockSpeed']} MT/s", f"{d['Manufacturer']} {d['PartNumber']}".strip()]
        for d in dimms
    ]
    return table(["Slot", "Capacity", "Rated", "Configured", "Part"], rows, ["---", "---:", "---:", "---:", "---"])


def block_disks(ctx: Mapping[str, Any]) -> str:
    disks = lookup(ctx, "phase0.feasibility.run_1.system.host.disks")
    if not isinstance(disks, list):
        return f"_{NOT_MEASURED}_"
    rows = [[d["FriendlyName"], d["BusType"], str(d["MediaType"]), iec(int(d["Size"]))] for d in disks]
    return table(["Disk", "Bus", "Media", "Size"], rows)


def block_telemetry(ctx: Mapping[str, Any]) -> str:
    t = lookup(ctx, "phase0.analysis.telemetry")
    ids = lookup(ctx, "phase0.analysis.run_ids")
    if not isinstance(t, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for rid, r in zip(ids, t):
        rows.append(
            [
                str(rid),
                f"{r['temperature_c']['min']:.0f}–{r['temperature_c']['max']:.0f} °C",
                f"{r['power_w']['min']:.0f}–{r['power_w']['max']:.0f} W",
                f"{r['graphics_clock_mhz']['min']:.0f}–{r['graphics_clock_mhz']['max']:.0f} MHz",
                ", ".join(f"Gen{g}" for g in r["pcie_link_gen_seen"]),
                ", ".join(f"x{w}" for w in r["pcie_link_width_seen"]),
            ]
        )
    return table(["Run", "GPU temp", "GPU power", "Graphics clock", "PCIe link gen seen", "Width"], rows)


def block_run_provenance(ctx: Mapping[str, Any]) -> str:
    prov = lookup(ctx, "phase0.analysis.run_provenance")
    ids = lookup(ctx, "phase0.analysis.run_ids")
    if not isinstance(prov, list):
        return f"_{NOT_MEASURED}_"
    rows = [[str(i), p["generated_at_utc"], f"`{(p['git_commit'] or '')[:7]}`", "yes" if p["git_dirty"] else "no"] for i, p in zip(ids, prov)]
    return table(["Run", "Finished (UTC)", "Commit", "Uncommitted tracked changes"], rows)


BLOCKS: dict[str, Callable[[Mapping[str, Any]], str]] = {
    name.removeprefix("block_"): fn for name, fn in globals().items() if name.startswith("block_") and callable(fn)
}


def render_all() -> dict[Path, str]:
    ctx = load_all()
    blocks = {name: fn(ctx) for name, fn in BLOCKS.items()}
    out: dict[Path, str] = {}
    for tmpl_name, rel in OUTPUTS.items():
        tmpl_path = TEMPLATES / tmpl_name
        if not tmpl_path.exists():
            continue
        body = render(tmpl_path.read_text(encoding="utf-8"), ctx, blocks)
        out[REPO_ROOT / rel] = GENERATED_BANNER.format(name=tmpl_name) + body
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if any rendered doc differs from disk")
    args = parser.parse_args()
    stale = []
    for path, text in render_all().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and stale:
        print("stale docs:", *[p.relative_to(REPO_ROOT) for p in stale], sep="\n  ")
        raise SystemExit(1)
    print(("checked" if args.check else "rendered"), len(render_all()), "docs;", len(stale), "changed")


if __name__ == "__main__":
    main()
