"""Render docs/templates/*.md.tmpl into the committed markdown docs.

All numbers come from results/**/metrics.json (hard rule 1). Tables are built here in
code; prose and scalar placeholders live in the templates.

    .venv\\Scripts\\python.exe scripts\\render_docs.py          # write docs
    .venv\\Scripts\\python.exe scripts\\render_docs.py --check  # exit 1 if any doc is stale
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from harness.render import NOT_MEASURED, iec, lookup, render  # noqa: E402
from harness.results import REPO_ROOT, load_all  # noqa: E402

TEMPLATES = REPO_ROOT / "docs" / "templates"

# template name -> output path (relative to repo root)
OUTPUTS = {
    "README.md.tmpl": "README.md",
    "SYSTEM_INFO.md.tmpl": "SYSTEM_INFO.md",
    "KV_MEMORY_MODEL.md.tmpl": "docs/KV_MEMORY_MODEL.md",
    "IMPLEMENTATION_PLAN.md.tmpl": "docs/IMPLEMENTATION_PLAN.md",
    "RESEARCH_LOG.md.tmpl": "docs/RESEARCH_LOG.md",
    "PHASE_0.md.tmpl": "docs/phases/PHASE_0.md",
    "PHASE_1.md.tmpl": "docs/phases/PHASE_1.md",
    "PHASE_2.md.tmpl": "docs/phases/PHASE_2.md",
    "PHASE_3.md.tmpl": "docs/phases/PHASE_3.md",
    "PHASE_4.md.tmpl": "docs/phases/PHASE_4.md",
    "PHASE_5.md.tmpl": "docs/phases/PHASE_5.md",
    "PHASE_6.md.tmpl": "docs/phases/PHASE_6.md",
    "PHASE_7.md.tmpl": "docs/phases/PHASE_7.md",
    "FINDINGS.md.tmpl": "docs/FINDINGS.md",
}

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/render_docs.py from docs/templates/{name}. "
    "Edit the template, not this file. Numbers come from results/**/metrics.json. -->\n\n"
)


# ---- formatting helpers ----------------------------------------------------------------


def gbps(v: float | None) -> str:
    return NOT_MEASURED if v is None else f"{v / 1e9:.2f}"


def rng(a: Mapping[str, Any] | None, fmt: Callable[[float], str], show_range: bool = True) -> str:
    """'median (min–max)' across independent runs."""
    if not a or not a.get("n_runs"):
        return NOT_MEASURED
    med = fmt(a["median"])
    if not show_range or a["n_runs"] < 2:
        return med
    return f"{med} ({fmt(a['min'])}–{fmt(a['max'])})"


def ms(v: float) -> str:
    return f"{v * 1e3:.3g} ms" if v < 1 else f"{v:.2f} s"


def table(header: list[str], rows: list[list[str]], align: list[str] | None = None) -> str:
    align = align or ["---"] * len(header)
    lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(align) + " |"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


# ---- blocks ------------------------------------------------------------------------------


def block_pcie_curve(ctx: Mapping[str, Any]) -> str:
    curve = lookup(ctx, "phase0.analysis.pcie.curve")
    if not isinstance(curve, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in curve:
        rows.append(
            [iec(r["size_bytes"])]
            + [rng(r[k], lambda v: f"{v / 1e9:.2f}") for k in ("pinned_h2d", "pinned_d2h", "pageable_h2d", "pageable_d2h")]
        )
    return table(
        ["Transfer size", "Pinned H2D", "Pinned D2H", "Pageable H2D", "Pageable D2H"],
        rows,
        ["---:", "---:", "---:", "---:", "---:"],
    )


def block_pcie_knees(ctx: Mapping[str, Any]) -> str:
    p = lookup(ctx, "phase0.analysis.pcie")
    if not isinstance(p, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = []
    for key, label in (("pinned_h2d", "Pinned H2D"), ("pinned_d2h", "Pinned D2H"), ("pageable_h2d", "Pageable H2D"), ("pageable_d2h", "Pageable D2H")):
        d = p[key]
        rows.append(
            [
                label,
                rng(d["asymptote_bps"], lambda v: f"{v / 1e9:.2f} GB/s"),
                rng(d["knee50_bytes"], iec),
                rng(d["knee80_bytes"], iec),
                rng(d["fit_t0_s"], lambda v: f"{v * 1e6:.0f} µs"),
                rng(d["fit_knee80_bytes"], iec),
            ]
        )
    return table(
        ["Path", "Asymptotic bandwidth", "50% knee (empirical)", "80% knee (empirical)", "Per-transfer overhead t0 (fit)", "80% knee (fit)"],
        rows,
        ["---", "---:", "---:", "---:", "---:", "---:"],
    )


def block_attention(ctx: Mapping[str, Any]) -> str:
    rows_in = lookup(ctx, "phase0.analysis.vram.decode_attention")
    if not isinstance(rows_in, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for a in rows_in:
        for name, b in a["backends"].items():
            best = " **(best)**" if name == a["best_backend"] else ""
            rows.append(
                [
                    f"{a['ctx_len']:,}",
                    f"`{name}`{best}",
                    rng(b["seconds_per_call"], ms),
                    rng(b["kv_scan_bps"], lambda v: f"{v / 1e9:.1f}"),
                    f"{b['max_rel_err_vs_math']:.1e}",
                    "yes" if b["correct"] else "**no**",
                ]
            )
    return table(
        ["Context (tokens, 1 layer)", "SDPA path", "Time per call", "KV scanned (GB/s)", "Max rel. error vs math", "Within tolerance"],
        rows,
        ["---:", "---", "---:", "---:", "---:", "---"],
    )


def block_overlap(ctx: Mapping[str, Any]) -> str:
    o = lookup(ctx, "phase0.analysis.overlap")
    if not isinstance(o, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [
        ["Compute kernel + pinned H2D", rng(o["compute_h2d_overlap"], lambda v: f"{v:.2f}")],
        ["Compute kernel + pinned D2H", rng(o["compute_d2h_overlap"], lambda v: f"{v:.2f}")],
        ["Pinned H2D + pinned D2H", rng(o["h2d_d2h_overlap"], lambda v: f"{v:.2f}")],
    ]
    return table(["Concurrent pair (separate CUDA streams)", "Overlap fraction (1 = max, 0 = sum)"], rows, ["---", "---:"])


def block_cpu_threads(ctx: Mapping[str, Any]) -> str:
    c = lookup(ctx, "phase0.analysis.cpu")
    if not isinstance(c, Mapping):
        return f"_{NOT_MEASURED}_"
    threads = c["threads"]
    rows = []
    for r in c["grid"]:
        rows.append([f"{r['tokens']:,}"] + [rng(r[f"partial_attn_t{t}"], ms, show_range=False) for t in threads])
    return table(["Tokens / layer"] + [f"{t} thr" for t in threads], rows, ["---:"] * (len(threads) + 1))


def block_cpu_vs_gpu(ctx: Mapping[str, Any]) -> str:
    c = lookup(ctx, "phase0.analysis.cpu.partial_attn_best")
    if not isinstance(c, list):
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            f"{r['tokens']:,}",
            rng(r["best_seconds"], ms),
            ", ".join(str(t) for t in r["best_threads"]),
            rng(r["gpu_fp32_seconds"], ms),
            rng(r["cpu_over_gpu"], lambda v: f"{v:.1f}×"),
        ]
        for r in c
    ]
    return table(
        ["Tokens / layer", "CPU best", "Best thread count per run", "GPU (same op, fp32)", "CPU / GPU"],
        rows,
        ["---:", "---:", "---", "---:", "---:"],
    )


def block_design(ctx: Mapping[str, Any]) -> str:
    d = lookup(ctx, "phase0.analysis.design")
    if not isinstance(d, Mapping) or not d.get("available"):
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in d["rows"]:
        rows.append(
            [
                f"{r['tokens_per_layer']:,}",
                iec(r["kv_bytes_per_layer_bf16"]),
                ms(r["fetch_one_transfer_s"]),
                ms(r["fetch_with_1thread_gather_s"]),
                ms(r["fetch_64tok_blocks_s"]),
                ms(r["gpu_attention_s"]) if "gpu_attention_s" in r else NOT_MEASURED,
                f"{r['fetch_over_gpu_attention']:.1f}×" if "fetch_over_gpu_attention" in r else "–",
                ms(r["cpu_partial_attn_s"]) if "cpu_partial_attn_s" in r else NOT_MEASURED,
                f"{r['cpu_over_fetch_one']:.1f}×" if "cpu_over_fetch_one" in r else "–",
                f"{r['cpu_over_fetch_blocks']:.1f}×" if "cpu_over_fetch_blocks" in r else "–",
            ]
        )
    return table(
        [
            "Non-resident tokens / layer",
            "KV bytes (bf16)",
            "(a) 1 transfer, already contiguous",
            "(a) 1-thread gather + 1 transfer",
            "(a) 64-token block transfers",
            "GPU attention (best kernel)",
            "contiguous fetch ÷ GPU attn",
            "(c) CPU partial attention",
            "(c) ÷ contiguous fetch",
            "(c) ÷ block fetch",
        ],
        rows,
        ["---:"] * 10,
    )


def block_nvidia_smi(ctx: Mapping[str, Any]) -> str:
    smi = lookup(ctx, "phase0.feasibility.run_1.system.software_gpu.nvidia_smi")
    if not isinstance(smi, Mapping):
        return f"_{NOT_MEASURED}_"
    return table(["nvidia-smi field", "Value"], [[f"`{k}`", str(v)] for k, v in smi.items()])


def block_hags(ctx: Mapping[str, Any]) -> str:
    host = lookup(ctx, "phase0.feasibility.run_1.system.host")
    if not isinstance(host, Mapping):
        return NOT_MEASURED
    v = host.get("hags_hwschmode")
    # The probe ran; a null means the registry value does not exist (Windows default).
    return {None: "registry value absent (Windows default)", 1: "1 (off)", 2: "2 (on)"}.get(v, str(v))


def block_env_vars(ctx: Mapping[str, Any]) -> str:
    env = lookup(ctx, "phase0.feasibility.run_1.system.software_gpu.env")
    if not isinstance(env, Mapping):
        return f"_{NOT_MEASURED}_"
    # None here means "unset in the benchmark process", which is a recorded fact, not a gap.
    return table(["Variable", "Value during benchmarks"], [[f"`{k}`", "(unset)" if v is None else f"`{v}`"] for k, v in env.items()])


def block_nvme(ctx: Mapping[str, Any]) -> str:
    n = lookup(ctx, "phase0.analysis.nvme")
    if not isinstance(n, Mapping) or not n.get("measured"):
        return f"_{NOT_MEASURED}_"
    rows = [
        ["Sequential, 1 MiB reads", rng(n["sequential_bps"], lambda v: f"{v / 1e9:.2f} GB/s"), "–"],
        [
            "Random 4 KiB",
            rng(n["random"]["4096"]["bps"], lambda v: f"{v / 1e6:.0f} MB/s"),
            rng(n["random"]["4096"]["iops"], lambda v: f"{v:,.0f}"),
        ],
        [
            "Random 128 KiB (one 64-token layer block)",
            rng(n["random"]["131072"]["bps"], lambda v: f"{v / 1e6:.0f} MB/s"),
            rng(n["random"]["131072"]["iops"], lambda v: f"{v:,.0f}"),
        ],
    ]
    return table(["Pattern (QD1, unbuffered)", "Throughput", "IOPS"], rows, ["---", "---:", "---:"])


def block_bandwidth_ladder(ctx: Mapping[str, Any]) -> str:
    a = lookup(ctx, "phase0.analysis")
    if not isinstance(a, Mapping):
        return f"_{NOT_MEASURED}_"
    big_attn = max(a["vram"]["decode_attention"], key=lambda r: r["ctx_len"])
    best = big_attn["backends"][big_attn["best_backend"]]["kv_scan_bps"]
    cpu64 = max(a["cpu"]["partial_attn_best"], key=lambda r: r["tokens"])
    kv_fp32 = 2 * cpu64["tokens"] * 8 * 64 * 4
    t = cpu64["best_seconds"]
    # Rate is 1/time, so the fastest run (min time) is the max rate.
    cpu_rate = {"n_runs": t["n_runs"], "median": kv_fp32 / t["median"], "min": kv_fp32 / t["max"], "max": kv_fp32 / t["min"]}
    rows = [
        ["VRAM device-to-device copy", rng(a["vram"]["d2d_copy_bps"], gbps)],
        [f"GPU decode attention KV scan (`{big_attn['best_backend']}`, {big_attn['ctx_len']:,} tokens)", rng(best, gbps)],
        ["PCIe pinned H2D (asymptote)", rng(a["pcie"]["pinned_h2d"]["asymptote_bps"], gbps)],
        ["PCIe pinned D2H (asymptote)", rng(a["pcie"]["pinned_d2h"]["asymptote_bps"], gbps)],
        ["PCIe pageable H2D (asymptote)", rng(a["pcie"]["pageable_h2d"]["asymptote_bps"], gbps)],
        ["Host memcpy, 1 thread", rng(a["cpu"]["host_memcpy_bps_1thread"], gbps)],
        [f"CPU partial attention KV rate (fp32, {cpu64['tokens']:,} tokens, best threads)", rng(cpu_rate, gbps)],
    ]
    if a["nvme"].get("measured"):
        rows += [
            ["NVMe sequential read", rng(a["nvme"]["sequential_bps"], gbps)],
            ["NVMe random 128 KiB read", rng(a["nvme"]["random"]["131072"]["bps"], gbps)],
        ]
    return table(["Path", "GB/s, median (min–max) across runs"], rows, ["---", "---:"])


def block_kv_models(ctx: Mapping[str, Any]) -> str:
    models = lookup(ctx, "phase0.kv_memory_model.models")
    if not isinstance(models, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for m in models:
        src = f"`{m['config_source']}`" + (" (mirror)" if m["used_mirror"] else "")
        rows.append(
            [
                f"**{m['key']}**",
                m["role"],
                src,
                str(m["num_hidden_layers"]),
                str(m["num_attention_heads"]),
                str(m["num_key_value_heads"]),
                str(m["head_dim"]),
                f"{m['gqa_group']}:1",
                iec(m["kv_bytes_per_token_bf16"]),
                iec(m["weights_bytes_safetensors"]) if m.get("weights_bytes_safetensors") else NOT_MEASURED,
            ]
        )
    return table(
        ["Model", "Role", "config.json source", "Layers", "Q heads", "KV heads", "head_dim", "GQA", "KV / token (bf16)", "Weights on disk"],
        rows,
        ["---", "---", "---", "---:", "---:", "---:", "---:", "---:", "---:", "---:"],
    )


def block_kv_contexts(ctx: Mapping[str, Any]) -> str:
    kv = lookup(ctx, "phase0.kv_memory_model")
    if not isinstance(kv, Mapping):
        return f"_{NOT_MEASURED}_"
    contexts = kv["contexts"]
    rows = [[f"**{m['key']}**"] + [iec(m["kv_bytes_by_context_bf16"][str(c)]) for c in contexts] for m in kv["models"]]
    return table(["Model"] + [f"{c // 1024}K" for c in contexts], rows, ["---"] + ["---:"] * len(contexts))


def block_kv_fit(ctx: Mapping[str, Any]) -> str:
    kv = lookup(ctx, "phase0.kv_memory_model")
    if not isinstance(kv, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = []
    for m in kv["models"]:
        fit = m.get("max_context_bf16_in_free_vram")
        rows.append(
            [
                f"**{m['key']}**",
                f"{m['max_position_embeddings']:,}" if m.get("max_position_embeddings") else NOT_MEASURED,
                f"{fit:,}" if fit is not None else NOT_MEASURED,
                f"{m['vocab_size']:,}",
                iec(m["prefill_logits_bytes_64k"]["bf16"]),
                iec(m["prefill_logits_bytes_64k"]["fp32"]),
            ]
        )
    return table(
        ["Model", "max_position_embeddings", "Max bf16 KV tokens in measured free VRAM (after weights)", "Vocab", "64K full logits (bf16)", "64K full logits (fp32)"],
        rows,
        ["---", "---:", "---:", "---:", "---:", "---:"],
    )


def block_budget_sweep(ctx: Mapping[str, Any]) -> str:
    s = lookup(ctx, "phase0.kv_memory_model.primary_budget_sweep")
    if not isinstance(s, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [[f"{100 * r['budget']:g}%", iec(r["gpu_kv_bytes"])] for r in s["rows"]]
    return table(["GPU KV budget", f"GPU-resident KV at {s['ctx_len'] // 1024}K ({s['model']}, bf16)"], rows, ["---:", "---:"])


def block_device_properties(ctx: Mapping[str, Any]) -> str:
    props = lookup(ctx, "phase0.feasibility.run_1.system.software_gpu.cuda_device_properties")
    if not isinstance(props, Mapping):
        return f"_{NOT_MEASURED}_"
    return table(["Field", "Value"], [[f"`{k}`", f"`{v}`"] for k, v in props.items()], ["---", "---"])


def block_driver_attributes(ctx: Mapping[str, Any]) -> str:
    attrs = lookup(ctx, "phase0.analysis.overlap.driver_attributes_run1")
    if not isinstance(attrs, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [[f"`CU_DEVICE_ATTRIBUTE_{k}`", str(v)] for k, v in attrs.items() if k not in ("ok", "source")]
    return table(["Driver attribute (cuDeviceGetAttribute)", "Value"], rows, ["---", "---:"])


def block_ram(ctx: Mapping[str, Any]) -> str:
    dimms = lookup(ctx, "phase0.feasibility.run_1.system.host.ram_dimms")
    if not isinstance(dimms, list):
        return f"_{NOT_MEASURED}_"
    rows = [
        [d.get("DeviceLocator") or "?", iec(int(d["Capacity"])), f"{d['Speed']} MT/s", f"{d['ConfiguredClockSpeed']} MT/s", f"{d['Manufacturer']} {d['PartNumber']}".strip()]
        for d in dimms
    ]
    return table(["Slot", "Capacity", "Rated", "Configured", "Part"], rows, ["---", "---:", "---:", "---:", "---"])


def block_disks(ctx: Mapping[str, Any]) -> str:
    disks = lookup(ctx, "phase0.feasibility.run_1.system.host.disks")
    if not isinstance(disks, list):
        return f"_{NOT_MEASURED}_"
    rows = [[d["FriendlyName"], d["BusType"], str(d["MediaType"]), iec(int(d["Size"]))] for d in disks]
    return table(["Disk", "Bus", "Media", "Size"], rows)


def block_telemetry(ctx: Mapping[str, Any]) -> str:
    t = lookup(ctx, "phase0.analysis.telemetry")
    ids = lookup(ctx, "phase0.analysis.run_ids")
    if not isinstance(t, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for rid, r in zip(ids, t):
        rows.append(
            [
                str(rid),
                f"{r['temperature_c']['min']:.0f}–{r['temperature_c']['max']:.0f} °C",
                f"{r['power_w']['min']:.0f}–{r['power_w']['max']:.0f} W",
                f"{r['graphics_clock_mhz']['min']:.0f}–{r['graphics_clock_mhz']['max']:.0f} MHz",
                ", ".join(f"Gen{g}" for g in r["pcie_link_gen_seen"]),
                ", ".join(f"x{w}" for w in r["pcie_link_width_seen"]),
            ]
        )
    return table(["Run", "GPU temp", "GPU power", "Graphics clock", "PCIe link gen seen", "Width"], rows)


def block_run_provenance(ctx: Mapping[str, Any]) -> str:
    prov = lookup(ctx, "phase0.analysis.run_provenance")
    ids = lookup(ctx, "phase0.analysis.run_ids")
    if not isinstance(prov, list):
        return f"_{NOT_MEASURED}_"
    rows = [[str(i), p["generated_at_utc"], f"`{(p['git_commit'] or '')[:7]}`", "yes" if p["git_dirty"] else "no"] for i, p in zip(ids, prov)]
    return table(["Run", "Finished (UTC)", "Commit", "Uncommitted tracked changes"], rows)


def block_p1_latency(ctx: Mapping[str, Any]) -> str:
    rows_in = lookup(ctx, "phase1.analysis.contexts")
    if not isinstance(rows_in, list):
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in rows_in:
        rows.append(
            [
                f"{r['ctx_len']:,}",
                rng(r["decode_wall_median_s"], ms),
                rng(r["decode_wall_p10_s"], ms, show_range=False) + " / " + rng(r["decode_wall_p90_s"], ms, show_range=False),
                rng(r["decode_tokens_per_s"], lambda v: f"{v:.1f}"),
                rng(r["ttft_cold_s"], lambda v: f"{v:.2f} s"),
                rng(r["ttft_warm_s"], lambda v: f"{v:.2f} s"),
                rng(r["prefill_tokens_per_s_warm"], lambda v: f"{v:,.0f}"),
                rng(r["peak_allocated_bytes"], iec, show_range=False),
                rng(r["gpu_resident_kv_bytes"], iec, show_range=False),
            ]
        )
    return table(
        ["Context", "Decode / token", "p10 / p90", "Tokens/s", "TTFT, plans cold", "TTFT, plans warm", "Prefill tok/s (warm)", "Peak allocated", "GPU KV resident"],
        rows,
        ["---:"] * 9,
    )


def block_p1_layer_split(ctx: Mapping[str, Any]) -> str:
    rows_in = lookup(ctx, "phase1.analysis.contexts")
    if not isinstance(rows_in, list):
        return f"_{NOT_MEASURED}_"
    us_ = lambda v: f"{v * 1e6:.0f} µs"  # noqa: E731
    rows = []
    for r in rows_in:
        p = r["per_layer_mean_s"]
        rows.append(
            [
                f"{r['ctx_len']:,}",
                rng(p["layer_s"], us_),
                rng(p["attention_kernel_s"], us_, show_range=False),
                rng(p["attention_other_s"], us_, show_range=False),
                rng(p["mlp_s"], us_, show_range=False),
                rng(p["other_s"], us_, show_range=False),
                f"{100 * r['attention_kernel_share_of_layer']:.0f}%" if r.get("attention_kernel_share_of_layer") is not None else NOT_MEASURED,
                rng(r["profiler_overhead_ratio"], lambda v: f"{v:.2f}×", show_range=False),
            ]
        )
    return table(
        ["Context", "Whole layer", "Attention kernel", "Attention: proj + RoPE + cache write", "MLP", "Norms + residual", "Kernel share", "Profiler overhead"],
        rows,
        ["---:"] * 8,
    )


def block_p1_window(ctx: Mapping[str, Any]) -> str:
    w = lookup(ctx, "phase1.analysis.window")
    if not isinstance(w, Mapping) or not w.get("available"):
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in w["rows"]:
        rows.append(
            [
                f"{r['ctx_len']:,}",
                ms(r["layer_window_s"]),
                ms(r["phase0_bound_attention_s"]) if "phase0_bound_attention_s" in r else "–",
                f"{r['window_over_phase0_bound']:.1f}×" if "window_over_phase0_bound" in r else "–",
                f"{r['tokens_fetchable_within_layer']:,.0f}",
                f"{100 * r['fetchable_fraction_within_layer']:.0f}%",
                f"{100 * r['phase0_fetchable_fraction']:.1f}%" if r.get("phase0_fetchable_fraction") is not None else "–",
                ms(r["fetch_all_one_layer_s"]),
            ]
        )
    return table(
        ["Context", "Measured layer window", "Phase 0 bound (attention only)", "Window ÷ bound", "Tokens fetchable in window", "Share of context", "Phase 0 share", "Fetch whole layer"],
        rows,
        ["---:"] * 8,
    )


def block_p1_strategies(ctx: Mapping[str, Any]) -> str:
    checks = lookup(ctx, "phase1.analysis.attention.checks")
    if not isinstance(checks, list):
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            f"`{c['strategy']}`",
            "yes" if c["ok"] else "**no**",
            f"{c['max_rel_err_decode']:.1e}" if c["max_rel_err_decode"] is not None else "–",
            f"{c['max_rel_err_prefill']:.1e}" if c["max_rel_err_prefill"] is not None else "–",
            ms(c["seconds_decode_growing_median"]) if c["seconds_decode_growing_median"] is not None else "–",
            ms(c["seconds_decode_growing_max"]) if c["seconds_decode_growing_max"] is not None else "–",
        ]
        for c in checks
    ]
    return table(
        ["Strategy", "Correct", "Rel. err decode", "Rel. err prefill", "Median call, KV growing by 1/step", "Max call"],
        rows,
        ["---", "---", "---:", "---:", "---:", "---:"],
    )


def block_p1_affinity(ctx: Mapping[str, Any]) -> str:
    a = lookup(ctx, "phase1.analysis.affinity")
    if not isinstance(a, Mapping):
        return f"_{NOT_MEASURED}_"
    names = {"default": "Default scheduling", "p_cores_only": "P-cores only", "e_cores_only": "E-cores only"}
    rows = [
        [names[k], f"`{c['mask']}`", ms(c["decode_wall_s"]["median"]), ms(c["p10_s"]), ms(c["p90_s"])]
        for k, c in a["conditions"].items()
    ]
    return table(["Affinity", "Mask", "Decode median", "p10", "p90"], rows, ["---", "---", "---:", "---:", "---:"])


QUALITY_LABELS = {
    "self_repeat": "Reference vs itself, fresh cache",
    "chunk_size_2048_vs_256": "Prefill chunk 2048 vs 256",
    "hf_stock_sdpa_dynamic_cache": "Stock transformers sdpa + DynamicCache vs reference",
    "fast_kernel_self_repeat": "`cudnn_bucketed` vs itself (the speed path's floor)",
    "fast_kernel_vs_quality": "`cudnn_bucketed` vs reference",
    "kernel_math_vs_quality": "Math kernel vs reference (chunk 256)",
}


def _quality_table(q: Mapping[str, Any], labels: Mapping[str, str]) -> str:
    rows = []
    for r in q["rows"]:
        for name, d in r["comparisons"].items():
            rows.append(
                [
                    f"{r['ctx_len']:,}",
                    labels.get(name, f"`{name}`"),
                    str(d["positions"]),
                    f"{100 * d['top1_agreement']:.1f}% [{100 * d['top1_ci95'][0]:.1f}, {100 * d['top1_ci95'][1]:.1f}]",
                    f"{d['mean_kl']:.2e} [{d['kl_ci95'][0]:.1e}, {d['kl_ci95'][1]:.1e}]",
                    f"{d['max_kl']:.2e}",
                    "**yes**" if d["exact_match"] else "no",
                ]
            )
    return table(
        ["Context", "Comparison", "Positions", "Top-1 agreement [95% CI]", "Mean KL, nats [95% CI]", "Max KL", "Bit-identical"],
        rows,
        ["---:", "---", "---:", "---:", "---:", "---:", "---"],
    )


def block_p1_quality(ctx: Mapping[str, Any]) -> str:
    q = lookup(ctx, "phase1.analysis.quality_reference")
    if not isinstance(q, Mapping):
        return f"_{NOT_MEASURED}_"
    return _quality_table(q, QUALITY_LABELS)


def block_p1_quality_first_run(ctx: Mapping[str, Any]) -> str:
    """The first run, whose reference was the cuDNN path, restricted to its self-comparison."""
    q = lookup(ctx, "phase1.analysis.quality_first_run")
    if not isinstance(q, Mapping):
        return f"_{NOT_MEASURED}_"
    only_self = {**q, "rows": [{**r, "comparisons": {"self_repeat": r["comparisons"]["self_repeat"]}} for r in q["rows"]]}
    return _quality_table(only_self, {"self_repeat": "`cudnn_bucketed` reference vs itself"})


def block_p1_kernel_repeatability(ctx: Mapping[str, Any]) -> str:
    k = lookup(ctx, "phase1.analysis.kernel_repeatability")
    if not isinstance(k, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            f"{r['ctx_len']:,}",
            f"`{r['strategy']}`",
            f"{r['decode_calls_checked']:,}",
            str(r["repeats_per_call"]),
            f"**{r['calls_not_repeatable']}**" if r["calls_not_repeatable"] else "0",
            f"{100 * r['fraction_not_repeatable']:.1f}%",
            ", ".join(str(x) for x in r["layers_affected"]) or "–",
        ]
        for r in k["rows"]
    ]
    return table(
        ["Context", "Strategy", "Decode attention calls", "Re-executions each", "Calls with >1 distinct output", "Share", "Layers affected"],
        rows,
        ["---:", "---", "---:", "---:", "---:", "---:", "---"],
    )


def block_p1_latency_regimes(ctx: Mapping[str, Any]) -> str:
    lr = lookup(ctx, "phase1.analysis.latency_regimes")
    if not isinstance(lr, Mapping):
        return f"_{NOT_MEASURED}_"
    names = {
        "os_default__nvidia_smi_on": ("OS-managed", "on"),
        "os_default__nvidia_smi_off": ("OS-managed", "off"),
        "opted_out__nvidia_smi_on": ("Opted out", "on"),
        "opted_out__nvidia_smi_off": ("Opted out", "off"),
    }
    rows = []
    for key, (thr, smi) in names.items():
        c = lr["conditions"].get(key)
        if c is None:
            continue
        rows.append(
            [
                thr,
                smi,
                f"{c['tokens']:,}",
                ms(c["decode_wall_s"]["median"]),
                ms(c["p90_s"]),
                f"{100 * c['slow_fraction']:.0f}%",
                ", ".join(f"{100 * x:.0f}%" for x in c["per_block_slow_fraction"]),
                f"{100 * c['p_core_fraction']:.0f}%",
                f"{100 * c['p_core_fraction_slow_tokens']:.0f}%" if c["p_core_fraction_slow_tokens"] is not None else "–",
            ]
        )
    return table(
        ["Power throttling", "nvidia-smi polling", "Tokens", "Median", "p90", "Slow tokens", "Slow share per block, in run order", "Tokens on P-cores", "Slow tokens on P-cores"],
        rows,
        ["---", "---", "---:", "---:", "---:", "---:", "---", "---:", "---:"],
    )


def block_p1_throttling_before_after(ctx: Mapping[str, Any]) -> str:
    t = lookup(ctx, "phase1.analysis.throttling_before_after")
    if not isinstance(t, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            f"{r['ctx_len']:,}",
            rng(r["decode_median_os_throttling_s"], ms),
            rng(r["decode_median_opted_out_s"], ms),
            f"{r['median_ratio_before_over_after']:.2f}×" if r["median_ratio_before_over_after"] is not None else NOT_MEASURED,
            rng(r["decode_p90_os_throttling_s"], ms, show_range=False),
            rng(r["decode_p90_opted_out_s"], ms, show_range=False),
        ]
        for r in t["rows"]
    ]
    return table(
        ["Context", "Median, OS-managed (first baseline)", "Median, opted out (reported baseline)", "Before ÷ after", "p90 before", "p90 after"],
        rows,
        ["---:"] * 6,
    )


def block_p1_affinity_before_after(ctx: Mapping[str, Any]) -> str:
    before = lookup(ctx, "phase1.analysis.affinity_os_throttling_summary")
    after = lookup(ctx, "phase1.analysis.affinity_summary")
    if not isinstance(after, Mapping):
        return f"_{NOT_MEASURED}_"
    names = {"default": "Default scheduling", "p_cores_only": "P-cores only", "e_cores_only": "E-cores only"}
    rows = []
    for k, label in names.items():
        a = after["conditions"][k]
        b = before["conditions"][k] if isinstance(before, Mapping) else None
        rows.append(
            [
                label,
                ms(a["median_s"]),
                f"{ms(a['p10_s'])} / {ms(a['p90_s'])}",
                ms(b["median_s"]) if b else NOT_MEASURED,
                f"{ms(b['p10_s'])} / {ms(b['p90_s'])}" if b else NOT_MEASURED,
            ]
        )
    return table(
        ["Affinity", "Median, throttling opted out", "p10 / p90", "Median, OS-managed (first run)", "p10 / p90"],
        rows,
        ["---", "---:", "---:", "---:", "---:"],
    )


def _provenance_row(label: str, p: Mapping[str, Any]) -> list[str]:
    dirty = p.get("git_dirty")
    files = p.get("git_dirty_files") or []
    return [label, p["generated_at_utc"], f"`{(p['git_commit'] or '')[:7]}`", ("yes: " + ", ".join(f"`{f}`" for f in files)) if dirty and files else ("yes" if dirty else "no")]


def block_p1_run_provenance(ctx: Mapping[str, Any]) -> str:
    prov = lookup(ctx, "phase1.analysis.run_provenance")
    ids = lookup(ctx, "phase1.analysis.run_ids")
    if not isinstance(prov, list):
        return f"_{NOT_MEASURED}_"
    return table(["Run", "Finished (UTC)", "Commit", "Uncommitted tracked changes"], [_provenance_row(str(i), p) for i, p in zip(ids, prov)])


def block_p1_supporting_provenance(ctx: Mapping[str, Any]) -> str:
    names = {
        "quality_reference": "Quality reference",
        "kernel_repeatability": "Kernel repeatability",
        "latency_regimes": "Latency regimes",
        "affinity": "Core affinity",
        "quality_reference_first_run": "Quality reference, first run (negative result)",
        "affinity_os_throttling": "Core affinity, before the throttling fix (negative result)",
    }
    rows = []
    for key, label in names.items():
        p = lookup(ctx, f"phase1.{key}.provenance")
        if isinstance(p, Mapping):
            rows.append(_provenance_row(label, p))
    before = lookup(ctx, "phase1.analysis.throttling_before_after.run_provenance_before")
    if isinstance(before, list):
        rows += [_provenance_row(f"Baseline run {i}, before the throttling fix (negative result)", p) for i, p in enumerate(before, 1)]
    if not rows:
        return f"_{NOT_MEASURED}_"
    return table(["Experiment", "Finished (UTC)", "Commit", "Uncommitted tracked changes"], rows)


POLICY_NAMES = {
    "full": "Full cache (rung 1)",
    "block_full": "Block pool, 100%",
    "window_sink": "Window + sink (rung 2)",
    "window": "Window, no sink (control)",
    "lru": "LRU (rung 3)",
    "h2o": "H2O-style (rung 4)",
    "quest": "Quest-style (rung 5)",
    "tiered_sync": "CPU tier, sync fetch (rung 6)",
    "tiered_prefetch": "CPU tier + prefetch (rung 7)",
    "tiered_int8": "CPU tier, int8 warm/cold (rung 8)",
    "tiered_exact": "CPU tier + exact CPU merge (rung 9)",
}


def _mib(v: float) -> str:
    return f"{v / 2**20:,.0f} MiB"


def _pct_budget(b: float) -> str:
    return f"{100 * b:g}%"


def _sweep_niah(ctx: Mapping[str, Any], phase: str) -> str:
    rows_in = lookup(ctx, f"{phase}.analysis.niah")
    if not isinstance(rows_in, list):
        return f"_{NOT_MEASURED}_"
    kinds = list(rows_in[0]["by_kind"])
    depths = list(rows_in[0]["by_depth"])
    rows = []
    for r in rows_in:
        rows.append(
            [
                POLICY_NAMES.get(r["policy"], r["policy"]),
                _pct_budget(r["budget"]),
                f"{100 * r['resident_fraction_median']:.1f}%",
                f"{100 * r['accuracy']:.1f}% [{100 * r['accuracy_ci95'][0]:.0f}, {100 * r['accuracy_ci95'][1]:.0f}]",
                # One decimal: the gate is a 99% threshold, and 98.8% must not round to it.
                f"{100 * r['retention']:.1f}%" if r["retention"] is not None else NOT_MEASURED,
            ]
            + [f"{100 * r['by_kind'][k]:.0f}%" for k in kinds]
            + [f"{100 * r['by_depth'][d]:.0f}%" for d in depths]
        )
    header = ["Policy", "Budget", "Resident at answer", "Accuracy [95% CI]", "Retention"] + [k for k in kinds] + [f"depth {float(d) * 100:g}%" for d in depths]
    return table(header, rows, ["---", "---:", "---:", "---:", "---:"] + ["---:"] * (len(kinds) + len(depths)))


def _sweep_teacher_forced(ctx: Mapping[str, Any], phase: str) -> str:
    rows_in = lookup(ctx, f"{phase}.analysis.teacher_forced")
    if not isinstance(rows_in, list):
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            POLICY_NAMES.get(r["policy"], r["policy"]),
            _pct_budget(r["budget"]),
            f"{100 * r['top1_agreement']:.1f}%",
            f"{100 * r['top1_min_doc']:.1f}%",
            f"{r['mean_kl']:.2e}",
            f"{r['mean_kl_max_doc']:.2e}",
            "**yes**" if r["exact_all_docs"] else "no",
        ]
        for r in rows_in
    ]
    return table(["Policy", "Budget", "Top-1 agreement (mean of documents)", "Worst document", "Mean KL, nats", "Worst document KL", "Bit-identical"], rows, ["---", "---:", "---:", "---:", "---:", "---:", "---"])


def _sweep_speed(ctx: Mapping[str, Any], phase: str) -> str:
    rows_in = lookup(ctx, f"{phase}.analysis.speed")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    ms_ = lambda v: f"{v * 1e3:.2f} ms"  # noqa: E731
    rows = []
    for r in rows_in:
        mgr = r["manager_host_s_per_token"]
        obs = r["manager_observe_s_per_token"]
        rows.append(
            [
                POLICY_NAMES.get(r["policy"], r["policy"]),
                _pct_budget(r["budget"]),
                rng(r["decode_wall_median_s"], ms_),
                rng(r["tokens_per_s"], lambda v: f"{v:.1f}", show_range=False),
                f"{r['over_full']:.2f}×" if r["over_full"] is not None else NOT_MEASURED,
                rng(r["decode_wall_p90_s"], ms_, show_range=False),
                rng(mgr, ms_, show_range=False) if mgr.get("n_runs") else "–",
                rng(obs, ms_, show_range=False) if obs.get("n_runs") else "–",
                rng(r["boundary_build_s"], ms_, show_range=False) if r["boundary_build_s"].get("n_runs") and r["policy"] != "full" else "–",
                rng(r["gpu_resident_kv_bytes"], _mib, show_range=False),
                rng(r["max_memory_allocated_bytes"], iec, show_range=False),
                "**yes**" if r["any_spill"] else "no",
            ]
        )
    return table(
        ["Policy", "Budget", "Decode / token (range over runs)", "Tokens/s", "÷ full", "p90", "Manager host time / token", "of which attention observation", "Boundary build", "Resident KV", "Peak allocated", "Spill"],
        rows,
        ["---", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---"],
    )


def _sweep_headline(ctx: Mapping[str, Any], phase: str) -> str:
    h = lookup(ctx, f"{phase}.analysis.headline")
    if not isinstance(h, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = []
    for policy, v in h.items():
        rows.append(
            [
                POLICY_NAMES.get(policy, policy),
                _pct_budget(v["min_budget_meeting_target"]) if v["min_budget_meeting_target"] is not None else "**none below 100%**",
                f"{v['tokens_per_s_at_that_budget']:.1f}" if v["tokens_per_s_at_that_budget"] is not None else "–",
                f"{100 * v['best_retention_below_full']:.1f}% at {_pct_budget(v['best_retention_budget'])}" if v["best_retention_below_full"] is not None else NOT_MEASURED,
            ]
        )
    return table(["Policy", "Smallest budget retaining ≥ 99% of full-cache NIAH accuracy", "Tokens/s there", "Best retention measured"], rows, ["---", "---:", "---:", "---:"])


def _sweep_provenance(ctx: Mapping[str, Any], phase: str) -> str:
    src = lookup(ctx, f"{phase}.analysis.sources")
    if not isinstance(src, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [_provenance_row("Policy quality (NIAH + teacher-forced)", src["policy_quality"])]
    rows += [_provenance_row(f"Budget speed run {i}", p) for i, p in enumerate(src["budget_speed"], 1)]
    return table(["Experiment", "Finished (UTC)", "Commit", "Uncommitted tracked changes"], rows)


# The budget-sweep tables are the same for Phase 2 and Phase 3; only the results directory differs.
def block_p2_niah(ctx: Mapping[str, Any]) -> str:
    return _sweep_niah(ctx, "phase2")


def block_p2_teacher_forced(ctx: Mapping[str, Any]) -> str:
    return _sweep_teacher_forced(ctx, "phase2")


def block_p2_speed(ctx: Mapping[str, Any]) -> str:
    return _sweep_speed(ctx, "phase2")


def block_p2_headline(ctx: Mapping[str, Any]) -> str:
    return _sweep_headline(ctx, "phase2")


def block_p2_provenance(ctx: Mapping[str, Any]) -> str:
    return _sweep_provenance(ctx, "phase2")


def block_p3_niah(ctx: Mapping[str, Any]) -> str:
    return _sweep_niah(ctx, "phase3")


def block_p3_teacher_forced(ctx: Mapping[str, Any]) -> str:
    return _sweep_teacher_forced(ctx, "phase3")


def block_p3_speed(ctx: Mapping[str, Any]) -> str:
    return _sweep_speed(ctx, "phase3")


def block_p3_headline(ctx: Mapping[str, Any]) -> str:
    return _sweep_headline(ctx, "phase3")


def block_p3_provenance(ctx: Mapping[str, Any]) -> str:
    return _sweep_provenance(ctx, "phase3")


def block_p3_paired(ctx: Mapping[str, Any]) -> str:
    paired = lookup(ctx, "phase3.analysis.paired_vs_reference")
    ref = lookup(ctx, "phase3.analysis.reference_policy")
    if not isinstance(paired, Mapping) or not paired:
        return f"_{NOT_MEASURED}_"
    budgets = [r["budget"] for r in next(iter(paired.values()))]
    rows = []
    for policy, entries in paired.items():
        cells = []
        for r in entries:
            lo, hi = r["ci95"]
            cells.append(f"{100 * r['accuracy_minus_reference']:+.1f} pp [{100 * lo:+.0f}, {100 * hi:+.0f}] ({r['prompts_better']}↑ {r['prompts_worse']}↓)")
        rows.append([f"{POLICY_NAMES.get(policy, policy)} − {POLICY_NAMES.get(str(ref), str(ref))}"] + cells)
    return table(["Accuracy difference [95% CI] (prompts better↑ worse↓)"] + [f"budget {_pct_budget(b)}" for b in budgets], rows, ["---"] + ["---:"] * len(budgets))


def block_p3_cross_speed(ctx: Mapping[str, Any]) -> str:
    rows_in = lookup(ctx, "phase3.analysis.cross_phase.speed")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    ms_ = lambda v: f"{v * 1e3:.2f} ms"  # noqa: E731
    rows = [
        [
            POLICY_NAMES.get(r["label"].split("@")[0], r["label"]),
            _pct_budget(float(r["label"].split("@")[1])),
            rng(r["phase2_decode_s"], ms_),
            rng(r["phase3_decode_s"], ms_),
            f"{r['ratio']:.3f}×" if r["ratio"] is not None else NOT_MEASURED,
        ]
        for r in rows_in
    ]
    return table(["Condition measured in both phases", "Budget", "Phase 2 decode / token", "Phase 3 decode / token", "Phase 3 ÷ Phase 2"], rows, ["---", "---:", "---:", "---:", "---:"])


def block_p3_h2o(ctx: Mapping[str, Any]) -> str:
    h = lookup(ctx, "phase3.analysis.h2o")
    if not isinstance(h, Mapping) or not h:
        return f"_{NOT_MEASURED}_"
    budgets = list(h["block0_resident_layers_min_by_budget"])
    rows = [
        ["Layers keeping block 0 (worst prompt), of " + str(h["layers"])] + [str(h["block0_resident_layers_min_by_budget"][b]) for b in budgets],
        ["Prompt blocks evicted at the boundary, all layers (median)"] + [f"{h['boundary_evicted_blocks_median_by_budget'][b]:,.0f}" for b in budgets],
        ["Decode-time evictions, all layers (median)"] + [f"{h['decode_evictions_median_by_budget'][b]:,.0f}" for b in budgets],
    ]
    return table(["H2O-style, NIAH prompts"] + [f"budget {float(b) * 100:g}%" for b in budgets], rows, ["---"] + ["---:"] * len(budgets))


def block_p4_niah(ctx: Mapping[str, Any]) -> str:
    return _sweep_niah(ctx, "phase4")


def block_p4_teacher_forced(ctx: Mapping[str, Any]) -> str:
    return _sweep_teacher_forced(ctx, "phase4")


def block_p4_speed(ctx: Mapping[str, Any]) -> str:
    return _sweep_speed(ctx, "phase4")


def block_p4_headline(ctx: Mapping[str, Any]) -> str:
    return _sweep_headline(ctx, "phase4")


def block_p4_provenance(ctx: Mapping[str, Any]) -> str:
    src = lookup(ctx, "phase4.analysis.sources")
    if not isinstance(src, Mapping):
        return f"_{NOT_MEASURED}_"
    rows = [_provenance_row("Policy quality (NIAH + teacher-forced)", src["policy_quality"])]
    rows += [_provenance_row(f"Budget speed, 2x slots, run {i}", p) for i, p in enumerate(src["budget_speed"], 1)]
    spare0 = lookup(ctx, "phase4.analysis.spare0.sources")
    if isinstance(spare0, list):
        rows += [_provenance_row(f"Budget speed, VRAM = attended, run {i}", p) for i, p in enumerate(spare0, 1)]
    return table(["Experiment", "Finished (UTC)", "Commit", "Uncommitted tracked changes"], rows)


def block_p4_identity(ctx: Mapping[str, Any]) -> str:
    ident = lookup(ctx, "phase4.analysis.identity_vs_quest")
    if not isinstance(ident, Mapping) or not ident:
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            POLICY_NAMES.get(pol, pol),
            f"{v['niah_answers_differing']} of {v['niah_prompt_conditions']}",
            f"{v['tf_max_abs_kl_diff']:.1e}" if v["tf_max_abs_kl_diff"] is not None else NOT_MEASURED,
            f"{100 * v['tf_max_abs_top1_diff']:.2f} pp" if v["tf_max_abs_top1_diff"] is not None else NOT_MEASURED,
        ]
        for pol, v in ident.items()
    ]
    return table(["Policy", "NIAH answers differing from rung 5 (prompt × budget)", "Largest teacher-forced KL difference", "Largest top-1 difference"], rows, ["---", "---:", "---:", "---:"])


def _tier_rows(speed: list[Mapping[str, Any]], tier: Mapping[str, Any], variant: str) -> list[list[str]]:
    by = {r["label"]: r for r in speed}
    rows = []
    for pol, per_budget in tier.items():
        for b_key, t in sorted(per_budget.items(), key=lambda kv: -float(kv[0])):
            if not t:
                continue
            sp = by.get(f"{pol}@{b_key}")
            q = by.get(f"quest@{b_key}")
            over = sp["decode_wall_median_s"]["median"] / q["decode_wall_median_s"]["median"] if sp and q else None
            pre = "–"
            if pol == "tiered_prefetch":
                pre = f"{100 * t['prefetch_precision']:.0f}% / {100 * t['prefetch_coverage']:.0f}%"
            rows.append([
                POLICY_NAMES.get(pol, pol),
                variant,
                _pct_budget(float(b_key)),
                f"{t['k_blocks']} / {t['n_slots']}",
                rng(sp["gpu_resident_kv_bytes"], _mib, show_range=False) if sp else NOT_MEASURED,
                rng(sp["decode_wall_median_s"], lambda v: f"{v * 1e3:.1f} ms") if sp else NOT_MEASURED,
                f"{over:.2f}×" if over is not None else NOT_MEASURED,
                f"{100 * t['hit_rate']:.1f}%",
                f"{t['fetched_pairs_per_token']:,.0f}",
                f"{t['fetch_mib_per_token']:.1f}",
                f"{t['fetch_transfers_per_token']:.1f}",
                f"{100 * t['thrash_share_of_fetches']:.0f}%",
                f"{t['host_rank_ms_per_token']:.1f}" if t.get("host_rank_ms_per_token") is not None else NOT_MEASURED,
                f"{t['host_select_ms_per_token'] - (t.get('host_rank_ms_per_token') or 0):.1f}",
                f"{t['host_prefetch_ms_per_token']:.1f}" if pol == "tiered_prefetch" else "–",
                pre,
            ])
    return rows


def block_p4_tier(ctx: Mapping[str, Any]) -> str:
    a = lookup(ctx, "phase4.analysis")
    if not isinstance(a, Mapping) or not a.get("tier"):
        return f"_{NOT_MEASURED}_"
    rows = _tier_rows(a["speed"], a["tier"], "2× slots")
    if a.get("spare0", {}).get("tier"):
        rows += _tier_rows(a["spare0"]["speed"], a["spare0"]["tier"], "= attended")
    header = [
        "Policy", "VRAM slots", "Budget", "K / slots per head", "Resident KV", "Decode / token (range over runs)", "÷ rung 5",
        "Hit rate", "Pairs fetched / token", "MiB fetched / token", "H2D transfers / token", "Thrash", "Rank + sync, ms",
        "Other select, ms", "Prefetch host, ms", "Prefetch precision / coverage",
    ]
    return table(header, rows, ["---", "---", "---:"] + ["---:"] * 13)


def block_p4_overlap(ctx: Mapping[str, Any]) -> str:
    rows = []
    for variant, key in (("2× slots", "phase4.analysis.prefetch_overlap"), ("= attended", "phase4.analysis.spare0.prefetch_overlap")):
        o = lookup(ctx, key)
        if not isinstance(o, Mapping):
            continue
        for b, v in o.items():
            rows.append([
                variant, _pct_budget(float(b)), f"{v['prefetches']:,}",
                f"{100 * v['overlap_fraction_median']:.0f}% (p10 {100 * v['overlap_fraction_p10']:.0f}%)",
                f"{100 * v['fully_hidden_share']:.1f}%",
                f"{v['copy_ms_median']:.2f} ms (p90 {v['copy_ms_p90']:.2f})",
                f"{v['window_ms_median']:.2f} ms",
                f"{100 * v['stalled_share']:.1f}%",
                f"{v['stall_ms_p90']:.2f} ms",
            ])
    if not rows:
        return f"_{NOT_MEASURED}_"
    return table(["VRAM slots", "Budget", "Prefetches timed", "Copy inside the window (median)", "Copies fully inside", "Copy duration", "Window (launch → target layer)", "Target layer waited", "Wait p90"], rows, ["---", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:"])


def block_p4_probe(ctx: Mapping[str, Any]) -> str:
    rows_in = lookup(ctx, "phase4.analysis.probe")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in rows_in:
        rows.append([
            f"`{r['probe']}`",
            POLICY_NAMES.get(r["policy"], r["policy"]),
            _pct_budget(r["budget"]),
            r["fetch"],
            f"{r['k_blocks']} / {r['n_slots']}",
            f"{r['decode_wall_median_s'] * 1e3:.1f} ms",
            f"{r['quest_decode_s'] * 1e3:.1f} ms" if r.get("quest_decode_s") else NOT_MEASURED,
            f"{r['full_decode_s'] * 1e3:.1f} ms" if r.get("full_decode_s") else NOT_MEASURED,
            f"{r['fetched_pairs_per_token']:,.0f}",
            f"{r['fetch_transfers_per_token']:,.0f}",
            f"{100 * r['thrash_share_of_fetches']:.0f}%",
            f"{r['host_fetch_ms_per_token']:.1f} ms",
            f"{100 * r['prefetch_precision']:.0f}%" if r["policy"] == "tiered_prefetch" else "–",
        ])
    return table(
        ["Probe", "Policy", "Budget", "Fetch", "K / slots", "Decode / token", "Rung 5, same run", "Full cache, same run", "Pairs fetched / token", "H2D transfers / token", "Thrash", "Fetch launch host time", "Prefetch precision"],
        rows,
        ["---", "---", "---:", "---", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:"],
    )


def block_p4_blocksize(ctx: Mapping[str, Any]) -> str:
    rows_in = lookup(ctx, "phase4.analysis.blocksize.rows")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    ms_ = lambda v: f"{v * 1e3:.1f} ms"  # noqa: E731
    rows = []
    for r in rows_in:
        t = r.get("tier") or {}
        rows.append([
            f"{r['block_size']}",
            POLICY_NAMES.get(r["policy"], r["policy"]),
            f"{t.get('k_blocks', '–')}",
            rng(r["decode_wall_median_s"], ms_, show_range=False),
            rng(r["tokens_per_s"], lambda v: f"{v:.1f}", show_range=False),
            rng(r["manager_host_s_per_token"], ms_, show_range=False),
            f"{100 * r['niah_accuracy']:.1f}%" if r["niah_accuracy"] is not None else NOT_MEASURED,
            f"{100 * r['niah_retention']:.1f}%" if r["niah_retention"] is not None else NOT_MEASURED,
            f"{r['tf_mean_kl']:.2e}" if r["tf_mean_kl"] is not None else NOT_MEASURED,
            f"{t['fetched_pairs_per_token']:,.0f}" if t else "–",
            f"{t['fetch_mib_per_token']:.1f}" if t else "–",
            f"{t['fetch_mean_transfer_kib']:.0f}" if t else "–",
            f"{100 * t['thrash_share_of_fetches']:.0f}%" if t else "–",
        ])
    return table(
        ["Block size", "Policy", "K blocks", "Decode / token", "Tokens/s", "Manager host / token", "NIAH accuracy", "Retention", "Mean KL", "Pairs fetched / token", "MiB fetched / token", "Mean transfer, KiB", "Thrash"],
        rows,
        ["---:", "---", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:", "---:"],
    )


# -- Phase 5: the int8 warm/cold tier (rung 8) ------------------------------------------------


def block_p5_niah(ctx: Mapping[str, Any]) -> str:
    return _sweep_niah(ctx, "phase5")


def block_p5_teacher_forced(ctx: Mapping[str, Any]) -> str:
    return _sweep_teacher_forced(ctx, "phase5")


def block_p5_speed(ctx: Mapping[str, Any]) -> str:
    return _sweep_speed(ctx, "phase5")


def block_p5_headline(ctx: Mapping[str, Any]) -> str:
    return _sweep_headline(ctx, "phase5")


def block_p5_provenance(ctx: Mapping[str, Any]) -> str:
    return _sweep_provenance(ctx, "phase5")


def block_p5_capacity(ctx: Mapping[str, Any]) -> str:
    """What rung 8 saves: stored off-GPU, pinned, and moved. The point of the phase."""
    rows_in = lookup(ctx, "phase5.analysis.capacity")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            _pct_budget(r["budget"]),
            f"{r['host_kv_mib_exact']:,.0f}",
            f"{r['host_kv_mib_int8']:,.0f}",
            f"{r['host_kv_ratio']:.3f}x" if r["host_kv_ratio"] is not None else NOT_MEASURED,
            f"{r['host_pinned_mib_exact']:,.0f}",
            f"{r['host_pinned_mib_int8']:,.0f}",
            f"{r['boundary_d2h_mib_exact']:,.0f}",
            f"{r['boundary_d2h_mib_int8']:,.0f}",
            f"{r['fetch_mib_per_token_exact']:.2f}",
            f"{r['fetch_mib_per_token_int8']:.2f}",
            f"{r['fetch_mib_ratio']:.2f}x" if r["fetch_mib_ratio"] is not None else NOT_MEASURED,
            f"{r['fetched_pairs_ratio']:.2f}x" if r["fetched_pairs_ratio"] is not None else NOT_MEASURED,
        ]
        for r in rows_in
    ]
    header = [
        "Budget", "Off-GPU KV, bf16 MiB", "int8 MiB", "Stored ratio", "Pinned, bf16 MiB", "int8 MiB",
        "Boundary D2H, bf16 MiB", "int8 MiB", "Fetched MiB/token, bf16", "int8", "Fetch ratio", "Pairs fetched ratio",
    ]
    return table(header, rows, ["---"] + ["---:"] * 11)


def block_p5_divergence(ctx: Mapping[str, Any]) -> str:
    """The quality axis rungs 6 and 7 did not have: how far rung 8 moved from the exact tier."""
    rows_in = lookup(ctx, "phase5.analysis.divergence_vs_exact")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    rows = [
        [
            _pct_budget(r["budget"]),
            f"{r['answers_differing']} of {r['prompts']}",
            f"{r['answers_broken']} / {r['answers_fixed']}",
            f"{100 * r['score_delta_mean']:+.1f} pp",
            f"{r['sign_test_p']:.2f}" if r.get("sign_test_p") is not None else NOT_MEASURED,
            f"{r['tf_mean_kl_exact']:.2e}" if r["tf_mean_kl_exact"] is not None else NOT_MEASURED,
            f"{r['tf_mean_kl']:.2e}" if r["tf_mean_kl"] is not None else NOT_MEASURED,
            f"{100 * r['tf_top1_agreement_exact']:.1f}%" if r["tf_top1_agreement_exact"] is not None else NOT_MEASURED,
            f"{100 * r['tf_top1_agreement']:.1f}%" if r["tf_top1_agreement"] is not None else NOT_MEASURED,
        ]
        for r in rows_in
    ]
    header = [
        "Budget", "NIAH answers differing from rung 6", "of which broken / fixed", "Mean NIAH score change",
        "Sign test p", "Teacher-forced KL, rung 6", "rung 8", "Top-1 agreement, rung 6", "rung 8",
    ]
    return table(header, rows, ["---"] + ["---:"] * 8)


def block_p5_host_time(ctx: Mapping[str, Any]) -> str:
    """Where rung 8's time goes. Ranking is unchanged by construction; fetching now dequantizes."""
    rows_in = lookup(ctx, "phase5.analysis.host_time")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    lat_in = lookup(ctx, "phase5.analysis.latency_vs_exact")
    lat = {r["budget"]: r for r in lat_in} if isinstance(lat_in, list) else {}
    f1 = lambda v: NOT_MEASURED if v is None else f"{v:.2f}"  # noqa: E731
    rows = []
    for r in rows_in:
        lr = lat.get(r["budget"], {})
        rows.append([
            _pct_budget(r["budget"]),
            f1(r["host_rank_ms_per_token_exact"]),
            f1(r["host_rank_ms_per_token_int8"]),
            f1(r["host_fetch_ms_per_token_exact"]),
            f1(r["host_fetch_ms_per_token_int8"]),
            f"{r['host_fetch_ms_per_token_delta']:+.2f}" if r["host_fetch_ms_per_token_delta"] is not None else NOT_MEASURED,
            f1(r["host_seal_ms_per_token_exact"]),
            f1(r["host_seal_ms_per_token_int8"]),
            f"{lr['ratio_median']:.3f}x" if lr.get("ratio_median") is not None else NOT_MEASURED,
            f"{lr['delta_ms_median']:+.1f} ms" if lr.get("delta_ms_median") is not None else NOT_MEASURED,
        ])
    header = [
        "Budget", "Rank + sync, ms (rung 6)", "rung 8", "Fetch, ms (rung 6)", "rung 8", "Fetch delta",
        "Seal, ms (rung 6)", "rung 8", "Decode / rung 6", "Decode delta",
    ]
    return table(header, rows, ["---"] + ["---:"] * 9)


def block_p5_tier(ctx: Mapping[str, Any]) -> str:
    """The Phase 4 tier table, with rung 6 rather than rung 5 as the denominator."""
    a = lookup(ctx, "phase5.analysis")
    if not isinstance(a, Mapping) or not a.get("tier"):
        return f"_{NOT_MEASURED}_"
    by = {r["label"]: r for r in a["speed"]}
    rows = []
    for pol, per_budget in a["tier"].items():
        for b_key, t in sorted(per_budget.items(), key=lambda kv: -float(kv[0])):
            if not t:
                continue
            sp = by.get(f"{pol}@{b_key}")
            ref = by.get(f"tiered_sync@{b_key}")
            over = sp["decode_wall_median_s"]["median"] / ref["decode_wall_median_s"]["median"] if sp and ref else None
            rows.append([
                POLICY_NAMES.get(pol, pol),
                _pct_budget(float(b_key)),
                f"{t['k_blocks']} / {t['n_slots']}",
                f"{t['pair_kib']:.1f}" if t.get("pair_kib") is not None else NOT_MEASURED,
                rng(sp["gpu_resident_kv_bytes"], _mib, show_range=False) if sp else NOT_MEASURED,
                f"{t['host_kv_mib']:,.0f}" if t.get("host_kv_mib") is not None else NOT_MEASURED,
                rng(sp["decode_wall_median_s"], lambda v: f"{v * 1e3:.1f} ms") if sp else NOT_MEASURED,
                f"{over:.2f}x" if over is not None else NOT_MEASURED,
                f"{100 * t['hit_rate']:.1f}%",
                f"{t['fetched_pairs_per_token']:,.0f}",
                f"{t['fetch_mib_per_token']:.2f}",
                f"{t['fetch_transfers_per_token']:.1f}",
                f"{100 * t['thrash_share_of_fetches']:.0f}%",
            ])
    header = [
        "Policy", "Budget", "K / slots per head", "Pair on the wire, KiB", "Resident KV", "Off-GPU KV, MiB",
        "Decode / token (range over runs)", "/ rung 6", "Hit rate", "Pairs fetched / token", "MiB fetched / token",
        "H2D transfers / token", "Thrash",
    ]
    return table(header, rows, ["---", "---:"] + ["---:"] * 11)


# -- Phase 7: rung 9, the exact merge (docs/phases/PHASE_7.md) --------------------------------


def block_p7_niah(ctx: Mapping[str, Any]) -> str:
    return _sweep_niah(ctx, "phase7")


def block_p7_teacher_forced(ctx: Mapping[str, Any]) -> str:
    return _sweep_teacher_forced(ctx, "phase7")


def block_p7_speed(ctx: Mapping[str, Any]) -> str:
    return _sweep_speed(ctx, "phase7")


def block_p7_headline(ctx: Mapping[str, Any]) -> str:
    return _sweep_headline(ctx, "phase7")


def block_p7_threads(ctx: Mapping[str, Any]) -> str:
    """The CPU thread count, measured inside a real decode rather than on an idle machine."""
    rows_in = lookup(ctx, "phase7.analysis.thread_sweep")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    best = min(r["decode_ms_per_token"] for r in rows_in)
    rows = []
    for r in rows_in:
        mark = " **(best)**" if r["decode_ms_per_token"] == best else ""
        rows.append([
            f"{int(r['threads'])}{mark}",
            f"{r['cpu_attention_ms_per_token']:.2f}",
            f"{r['merge_ms_per_token']:.2f}",
            f"{r['decode_ms_per_token']:.2f}",
            f"{r['decode_ms_per_token'] / best:.2f}x",
        ])
    return table(
        ["torch CPU threads", "CPU pass, ms/token", "Merge total, ms/token", "Decode, ms/token", "x the best"],
        rows,
        ["---:", "---:", "---:", "---:", "---:"],
    )


def block_p7_provenance(ctx: Mapping[str, Any]) -> str:
    return _sweep_provenance(ctx, "phase7")


def block_p7_distance(ctx: Mapping[str, Any]) -> str:
    """How far each rung's output sits from the full cache's, on the same prompts."""
    rows_in = lookup(ctx, "phase7.analysis.distance_from_full")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in sorted(rows_in, key=lambda r: (r["policy"] != "tiered_exact", -r["budget"])):
        rows.append([
            POLICY_NAMES.get(r["policy"], r["policy"]),
            _pct_budget(r["budget"]),
            f"{r['answers_differing']} of {r['prompts']}",
            f"{r['answers_broken']} / {r['answers_fixed']}",
            f"{100 * r['score_delta_mean']:+.1f} pp",
            f"{r['tf_mean_kl']:.2e}" if r["tf_mean_kl"] is not None else NOT_MEASURED,
            f"{100 * r['tf_top1_agreement']:.1f}%" if r["tf_top1_agreement"] is not None else NOT_MEASURED,
        ])
    header = [
        "Rung", "Budget", "NIAH answers differing from the full cache", "of which broken / fixed",
        "Mean NIAH score change", "Teacher-forced KL", "Top-1 agreement",
    ]
    return table(header, rows, ["---", "---:", "---:", "---:", "---:", "---:", "---:"])


def block_p7_price(ctx: Mapping[str, Any]) -> str:
    """What rung 9 costs against the rung it replaces and against the cache it reproduces."""
    rows_in = lookup(ctx, "phase7.analysis.price")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    f2 = lambda v: NOT_MEASURED if v is None else f"{v:.2f}"  # noqa: E731
    rows = []
    for r in sorted(rows_in, key=lambda r: -r["budget"]):
        rows.append([
            _pct_budget(r["budget"]),
            f2(r["approx_ms_per_token"]),
            f2(r["exact_ms_per_token"]),
            f2(r["added_ms_per_token"]),
            f"**{r['over_approx']:.2f}x**" if r["over_approx"] is not None else NOT_MEASURED,
            f"{r['over_full']:.2f}x" if r["over_full"] is not None else NOT_MEASURED,
            f"{r['resident_mib_exact']:,.0f}" if r["resident_mib_exact"] is not None else NOT_MEASURED,
            f"{r['host_pinned_mib']:,.0f}" if r["host_pinned_mib"] is not None else NOT_MEASURED,
            f"{r['mirror_mib']:,.0f}" if r["mirror_mib"] is not None else NOT_MEASURED,
        ])
    header = [
        "Budget", "Rung 6, ms/token", "Rung 9, ms/token", "Added, ms", "x rung 6", "x the full cache",
        "Resident KV, MiB", "Pinned host, MiB", "float32 mirror, MiB",
    ]
    return table(header, rows, ["---:"] + ["---:"] * 8)


def block_p7_cpu(ctx: Mapping[str, Any]) -> str:
    """Where rung 9's added time goes, and whether the CPU pass responds to the budget."""
    rows_in = lookup(ctx, "phase7.analysis.exact")
    prices = lookup(ctx, "phase7.analysis.price")
    if not isinstance(rows_in, Mapping) or not rows_in:
        return f"_{NOT_MEASURED}_"
    added = {f"{r['budget']:g}": r for r in prices} if isinstance(prices, list) else {}
    f2 = lambda v: NOT_MEASURED if v is None else f"{v:.2f}"  # noqa: E731
    rows = []
    for key in sorted(rows_in, key=lambda k: -float(k)):
        r = rows_in[key]
        if not r:
            continue
        a = added.get(key, {})
        rows.append([
            _pct_budget(float(key)),
            f2(r.get("cpu_attention_ms_per_token")),
            f2(r.get("cpu_attention_ms_per_layer")),
            f2(r.get("merge_overhead_ms_per_token")),
            f2(r.get("mirror_ms_per_token")),
            f"{a['added_explained_share']:.0%}" if a.get("added_explained_share") is not None else NOT_MEASURED,
            f"{r['cold_tokens_per_merge']:,.0f} of {r['cpu_tokens_per_merge']:,.0f}" if r.get("cpu_tokens_per_merge") else NOT_MEASURED,
            f2(r.get("returned_kib_per_token")),
        ])
    header = [
        "Budget", "CPU pass, ms/token", "ms per selecting layer", "Merge overhead, ms/token",
        "Mirror write, ms/token", "Share of the added time explained", "Cold of attended token-heads per merge",
        "Returned from the CPU, KiB/token",
    ]
    return table(header, rows, ["---:"] + ["---:"] * 7)


# -- Phase 6: the replay ablation (docs/phases/PHASE_6.md) -------------------------------------


def block_p6_ceiling(ctx: Mapping[str, Any]) -> str:
    """Per condition: what the replay removed, and what it was worth."""
    rows_in = lookup(ctx, "phase5.ceiling.conditions")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    f2 = lambda v: NOT_MEASURED if v is None else f"{v:.2f}"  # noqa: E731
    rows = []
    for r in sorted(rows_in, key=lambda r: (r["policy"] != "full", r["policy"], -r["budget"])):
        rows.append([
            POLICY_NAMES.get(r["policy"], r["policy"]),
            _pct_budget(r["budget"]),
            f2(r["decode_ms"]),
            f2(r["replay_ms"]),
            f2(r["saved_ms"]),
            f"**{r['ceiling_speedup']:.2f}x**" if r["ceiling_speedup"] is not None else "-",
            f2(r.get("rank_ms_counted")),
            f2(r.get("saved_vs_counted_rank_ms")),
            f"{r['fetched_pairs']:,.0f} = {r['replay_fetched_pairs']:,.0f}" if r["fetched_pairs_match"] else ("-" if r["fetched_pairs"] is None else "**differ**"),
            f"{100 * r['token_agreement']:.1f}%" if r["token_agreement"] is not None else "-",
        ])
    header = [
        "Condition", "Budget", "Decode, ms/token", "Replay, ms/token", "Saved, ms", "Ceiling",
        "Rank+sync counted, ms", "Saved - counted, ms", "Pairs fetched", "Replay token agreement",
    ]
    return table(header, rows, ["---", "---:"] + ["---:"] * 8)


def block_p6_gap(ctx: Mapping[str, Any]) -> str:
    """The instrument that did not work, kept because it says where the stall is."""
    rows_in = lookup(ctx, "phase5.ceiling.conditions")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in sorted(rows_in, key=lambda r: (r["policy"] != "full", r["policy"], -r["budget"])):
        excess = r["inter_layer_gap_excess_ms"]
        saved = r["saved_ms"]
        rows.append([
            POLICY_NAMES.get(r["policy"], r["policy"]),
            _pct_budget(r["budget"]),
            f"{r['inter_layer_gap_ms']:.3f}" if r["inter_layer_gap_ms"] is not None else NOT_MEASURED,
            f"{excess:.3f}" if excess is not None else NOT_MEASURED,
            f"{100 * excess / saved:.0f}%" if excess is not None and saved else "-",
        ])
    return table(
        ["Condition", "Budget", "Inter-layer GPU gap, ms/token", "Excess over the full cache, ms", "Share of the saving it explains"],
        rows,
        ["---", "---:", "---:", "---:", "---:"],
    )


def block_p6_provenance(ctx: Mapping[str, Any]) -> str:
    rows = []
    for p in lookup(ctx, "phase5.ceiling.sources") or []:
        if isinstance(p, Mapping):
            rows.append(_provenance_row("Replay ablation run", p))
    for label, key in (("Ceiling analysis", "phase5.ceiling.provenance"), ("Ladder analysis", "ladder.provenance")):
        p = lookup(ctx, key)
        if isinstance(p, Mapping):
            rows.append(_provenance_row(label, p))
    if not rows:
        return f"_{NOT_MEASURED}_"
    return table(["Artifact", "Finished (UTC)", "Commit", "Uncommitted tracked changes"], rows)


# -- The consolidated ladder (docs/FINDINGS.md) ------------------------------------------------


def block_ladder_headline(ctx: Mapping[str, Any]) -> str:
    """Brief §B8's headline question, per rung."""
    best = lookup(ctx, "ladder.best")
    if not isinstance(best, Mapping) or not best:
        return f"_{NOT_MEASURED}_"
    rows = []
    for key in sorted(best, key=int):
        v = best[key]
        rows.append([
            key,
            v["name"],
            _pct_budget(v["min_budget_meeting_target"]) if v["min_budget_meeting_target"] is not None else "**none**",
            f"{100 * v['best_retention']:.1f}%" if v["best_retention"] is not None else NOT_MEASURED,
            _pct_budget(v["best_retention_budget"]) if v["best_retention_budget"] is not None else NOT_MEASURED,
            f"{v['resident_mib_at_best']:,.0f}" if v["resident_mib_at_best"] is not None else NOT_MEASURED,
            f"{v['tokens_per_s_at_best']:.1f}" if v["tokens_per_s_at_best"] is not None else NOT_MEASURED,
        ])
    header = ["Rung", "Policy", "Smallest budget retaining >= 99%", "Best retention measured", "at budget", "Resident KV, MiB", "Tokens/s there"]
    return table(header, rows, ["---:", "---", "---:", "---:", "---:", "---:", "---:"])


def block_ladder_table(ctx: Mapping[str, Any]) -> str:
    """Every rung at every budget: the frontier as numbers."""
    rows_in = lookup(ctx, "ladder.rows")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in sorted(rows_in, key=lambda r: (r["rung"], -r["budget"], r["slots"] or "")):
        rows.append([
            str(r["rung"]),
            r["name"],
            r["slots"] or "-",
            _pct_budget(r["budget"]),
            f"{100 * r['accuracy']:.1f}% [{100 * r['accuracy_ci95'][0]:.0f}, {100 * r['accuracy_ci95'][1]:.0f}]",
            f"{100 * r['retention']:.1f}%" if r["retention"] is not None else NOT_MEASURED,
            f"{r['resident_mib']:,.0f}" if r["resident_mib"] is not None else NOT_MEASURED,
            f"{r['tokens_per_s']:.1f}" if r["tokens_per_s"] is not None else NOT_MEASURED,
            r["phase"].replace("phase", "Phase "),
        ])
    header = ["Rung", "Policy", "VRAM slots", "Budget", "NIAH accuracy [95% CI]", "Retention", "Resident KV, MiB", "Tokens/s", "Measured in"]
    return table(header, rows, ["---:", "---", "---", "---:", "---:", "---:", "---:", "---:", "---"])


def block_ladder_repeatability(ctx: Mapping[str, Any]) -> str:
    """Conditions measured in more than one phase, and how far those phases disagree."""
    rows_in = lookup(ctx, "ladder.repeatability")
    if not isinstance(rows_in, list) or not rows_in:
        return f"_{NOT_MEASURED}_"
    rows = []
    for r in sorted(rows_in, key=lambda r: (r["policy"], -r["budget"])):
        rows.append([
            POLICY_NAMES.get(r["policy"], r["policy"]),
            _pct_budget(r["budget"]),
            ", ".join(p.replace("phase", "P") for p in r["phases"]),
            f"{r['accuracy_max_gap_pp']:.2f} pp",
            f"{r['tokens_per_s_max_ratio']:.3f}x" if r["tokens_per_s_max_ratio"] is not None else "-",
        ])
    return table(["Condition", "Budget", "Phases", "Largest accuracy gap", "Largest tokens/s ratio"], rows, ["---", "---:", "---", "---:", "---:"])


BLOCKS: dict[str, Callable[[Mapping[str, Any]], str]] = {
    name.removeprefix("block_"): fn for name, fn in globals().items() if name.startswith("block_") and callable(fn)
}


def render_all() -> dict[Path, str]:
    ctx = load_all()
    blocks = {name: fn(ctx) for name, fn in BLOCKS.items()}
    out: dict[Path, str] = {}
    for tmpl_name, rel in OUTPUTS.items():
        tmpl_path = TEMPLATES / tmpl_name
        if not tmpl_path.exists():
            continue
        body = render(tmpl_path.read_text(encoding="utf-8"), ctx, blocks)
        out[REPO_ROOT / rel] = GENERATED_BANNER.format(name=tmpl_name) + body
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if any rendered doc differs from disk")
    args = parser.parse_args()
    stale = []
    for path, text in render_all().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if args.check and stale:
        print("stale docs:", *[p.relative_to(REPO_ROOT) for p in stale], sep="\n  ")
        raise SystemExit(1)
    print(("checked" if args.check else "rendered"), len(render_all()), "docs;", len(stale), "changed")


if __name__ == "__main__":
    main()
